Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,19 +16,17 @@ jobs:
       with:
         python-version: '3.9'
 
-    - name: Check for requirements.txt
-      run: |
-        if [ -f "requirements.txt" ]; then
-          echo "requirements.txt found."
-        else
-          echo "requirements.txt not found!"
-          exit 1
-        fi
+    - name: Upgrade pip
+      run: python -m pip install --upgrade pip
 
     - name: Install dependencies
       run: |
-        python -m pip install --upgrade pip
-        pip install -r requirements.txt
+        if [ -f "YukkiMusic/requirements.txt" ]; then
+          pip install -r YukkiMusic/requirements.txt
+        else
+          echo "Error: requirements.txt not found in YukkiMusic directory!"
+          exit 1
+        fi
 
     - name: Run YukkiMusic Bot
       run: python YukkiMusic/__main__.py
