Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -1,41 +1,36 @@
-name: Python application
+name: Run YukkiMusic Bot
 
 on:
-  push:
-    branches: [ main ]
-  pull_request:
-    branches: [ main ]
   workflow_dispatch:
 
 jobs:
   build:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Checkout code
-        uses: actions/checkout@v2
+    - name: Check out the repository
+      uses: actions/checkout@v2
 
-      - name: Set up Python
-        uses: actions/setup-python@v2
-        with:
-          python-version: '3.9'
+    - name: Set up Python
+      uses: actions/setup-python@v2
+      with:
+        python-version: '3.9'
 
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          if [ -f "YukkiMusic/requirements.txt" ]; then
-            # تثبيت المكتبات من requirements.txt
-            pip install -r YukkiMusic/requirements.txt || {
-              echo "خطأ في تثبيت المكتبات، سوف أقوم بتحديث المكتبات."
-              pip install --upgrade --force-reinstall -r YukkiMusic/requirements.txt
-            }
-          else
-            echo "requirements.txt غير موجود في دليل YukkiMusic!"
-            exit 1
-          fi
+    - name: Upgrade pip
+      run: python -m pip install --upgrade pip
 
-      - name: Check and update requirements
-        run: |
-          pip freeze > YukkiMusic/requirements.txt
+    - name: Install required packages
+      run: |
+        if [ -f "YukkiMusic/requirements.txt" ]; then
+          pip install -r YukkiMusic/requirements.txt || {
+            echo "Fixing dependencies in requirements.txt..."
+            sed -i 's/pytgcalls==1.2.0/pytgcalls>=0.0.2,<1.3.0/' YukkiMusic/requirements.txt
+            pip install -r YukkiMusic/requirements.txt
+          }
+        else
+          echo "requirements.txt not found in YukkiMusic directory!"
+          exit 1
+        fi
 
-      - name: Run bot
-        run: python YukkiMusic/__main__.py
+    - name: Run the bot
+      run: python YukkiMusic/__main__.py
